# Generated by Django 2.0.6 on 2018-06-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinnedmessage',
            name='message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
