# Generated by Django 2.0.6 on 2018-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_recipient_sentpinnedmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentpinnedmessage',
            name='pinned_message',
        ),
        migrations.AddField(
            model_name='pinnedmessage',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Pinned message has been mailed'),
        ),
        migrations.DeleteModel(
            name='SentPinnedMessage',
        ),
    ]
