# Generated by Django 2.0.6 on 2018-06-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20180607_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
