# Generated by Django 2.0.6 on 2018-06-08 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_configuration_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinnedmessage',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
