# Generated by Django 2.0.6 on 2018-06-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_pinnedmessage_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='login_code',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
